insert into book_information values ("book1", "Harry Potter and the Philosopher's Stone", "JK Rowling", 856015990)
insert into book_information values ("book2", "Harry Potter and the Chamber of Secrets", "JK Rowling", 887551990)
insert into book_information values ("book3", "Harry Potter and the Prisoner of Azkaban", "JK Rowling", 919087990)
insert into book_information values ("book4", "Harry Potter and the Goblet of Fire", "JK Rowling", 950623990)
insert into book_information values ("book5", "Harry Potter and the Order of the Phoenix", "JK Rowling", 1045318390)
insert into book_information values ("book6", "Harry Potter and the Half-Blood Prince", "JK Rowling", 1108476790)
insert into book_information values ("book7", "Harry Potter and the Deathly Hallows", "JK Rowling", 1171548790)
insert into book_information values ("book8", "Harry Potter and the Cursed Child", "JK Rowling", 1455545590)
insert into book_information values ("book9", "The Lord of the Rings - The Fellowship of the Ring", "JRR Tolkien", -500982410)
insert into book_information values ("book10", "The Lord of the Rings - The Two Towers", "JRR Tolkien", -500982410)
insert into book_information values ("book11", "The Lord of the Rings - The Return of the King", "JRR Tolkien", -469446410)
